# CircleCIのプロジェクト設定の、Advanced Settings -> Only build pull requestsをOnに
version: 2

defaults: &defaults
  working_directory: ~/dncngrl
  docker:
    - image: circleci/node:8.9.4

jobs:
  build-publish:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - dncngrl-{{ checksum "yarn.lock" }}
            - dncngrl-

      - run:
          name: Install node packages
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          key: dncngrl-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Build
          command: yarn run build

      - run:
          name: Erase and move files
          command: |
            find . -maxdepth 1 -type f -not -name '.gitmodules' | xargs rm -rf
            find . -maxdepth 1 -type d -not -name '.' -not -name '.git' -not -name 'server' -not -name 'theme' | xargs rm -rf

      - deploy:
          name: Publish
          command: |
            git config --global user.name  "CircleCI"
            git config --global user.email "circleci@dncngrl.com"
            git add .
            git commit -m "Publish by CircleCI"
            git checkout -B public
            git push -u origin public --force

workflows:
  version: 2

  deploy:
    jobs:
      - build-publish:
          # masterへpull requestがmergeされたとき(masterにcommitがあったとき)
          filters:
            branches:
              only: master
